import fs from 'fs';
import chalk from 'chalk';

export function createDocumentationFiles(projectName, modules, options) {
    const { includeSwagger, includePostmanCollection } = options;
    const files = [];

    if (includeSwagger) {
        files.push({
            path: 'docs/swagger.json',
            content: JSON.stringify({
                "openapi": "3.0.0",
                "info": {
                    "title": `${projectName} API`,
                    "description": "API documentation generated by Baax",
                    "version": "1.0.0"
                },
                "servers": [{ "url": "http://localhost:3000/api" }],
                "components": {
                    "securitySchemes": {
                        "bearerAuth": { "type": "http", "scheme": "bearer" }
                    }
                },
                "paths": {
                    "/": {
                        "get": {
                            "summary": "API Information",
                            "responses": { "200": { "description": "API info" } }
                        }
                    }
                }
            }, null, 2)
        });
    }

    if (includePostmanCollection) {
        files.push({
            path: 'postman-collection.json',
            content: JSON.stringify({
                "info": {
                    "name": `${projectName} API`,
                    "description": "Postman collection for testing"
                },
                "variable": [
                    { "key": "base_url", "value": "http://localhost:3000/api" }
                ]
            }, null, 2)
        });
    }

    files.forEach(({ path, content }) => {
        fs.writeFileSync(path, content);
        console.log(chalk.green(`Created file: ${path}`));
    });
}